#!/bin/bash

printf "%-10s %-25s %s\n"      "%%"            "`date +"%%"`"       "a literal %"
printf "%-10s %-25s %s\n"      "%a"            "`date +"%a"`"       "locale's abbreviated weekday name (e.g., Sun)"
printf "%-10s %-25s %s\n"      "%A"            "`date +"%A"`"       "locale's full weekday name (e.g., Sunday)"
printf "%-10s %-25s %s\n"      "%b"            "`date +"%b"`"       "locale's abbreviated month name (e.g., Jan)"
printf "%-10s %-25s %s\n"      "%B"            "`date +"%B"`"       "locale's full month name (e.g., January)"
printf "%-10s %-25s %s\n"      "%c"            "`date +"%c"`"       "locale's date and time (e.g., Thu Mar  3 23:05:25 2005)"
printf "%-10s %-25s %s\n"      "%C"            "`date +"%C"`"       "century; like %Y, except omit last two digits (e.g., 21)"
printf "%-10s %-25s %s\n"      "%d"            "`date +"%d"`"       "day of month (e.g, 01)"
printf "%-10s %-25s %s\n"      "%D"            "`date +"%D"`"       "date; same as %m/%d/%y"
printf "%-10s %-25s %s\n"      "%e"            "`date +"%e"`"       "day of month, space padded; same as %_d"
printf "%-10s %-25s %s\n"      "%F"            "`date +"%F"`"       "full date; same as %Y-%m-%d"
printf "%-10s %-25s %s\n"      "%g"            "`date +"%g"`"       "last two digits of year of ISO week number (see %G)"
printf "%-10s %-25s %s\n"      "%G"            "`date +"%G"`"       "year of ISO week number (see %V); normally useful only with %V"
printf "%-10s %-25s %s\n"      "%h"            "`date +"%h"`"       "same as %b"
printf "%-10s %-25s %s\n"      "%H"            "`date +"%H"`"       "hour (00..23)"
printf "%-10s %-25s %s\n"      "%I"            "`date +"%I"`"       "hour (01..12)"
printf "%-10s %-25s %s\n"      "%j"            "`date +"%j"`"       "day of year (001..366)"
printf "%-10s %-25s %s\n"      "%k"            "`date +"%k"`"       "hour ( 0..23)"
printf "%-10s %-25s %s\n"      "%l"            "`date +"%l"`"       "hour ( 1..12)"
printf "%-10s %-25s %s\n"      "%m"            "`date +"%m"`"       "month (01..12)"
printf "%-10s %-25s %s\n"      "%M"            "`date +"%M"`"       "minute (00..59)"
printf "%-10s %-25s %s\n"      "%n"            "`date +"%n"`"       "a newline"
printf "%-10s %-25s %s\n"      "%N"            "`date +"%N"`"       "nanoseconds (000000000..999999999)"
printf "%-10s %-25s %s\n"      "%p"            "`date +"%p"`"       "locale's equivalent of either AM or PM; blank if not known"
printf "%-10s %-25s %s\n"      "%P"            "`date +"%P"`"       "like %p, but lower case"
printf "%-10s %-25s %s\n"      "%r"            "`date +"%r"`"       "locale's 12-hour clock time (e.g., 11:11:04 PM)"
printf "%-10s %-25s %s\n"      "%R"            "`date +"%R"`"       "24-hour hour and minute; same as %H:%M"
printf "%-10s %-25s %s\n"      "%s"            "`date +"%s"`"       "seconds since 1970-01-01 00:00:00 UTC"
printf "%-10s %-25s %s\n"      "%S"            "`date +"%S"`"       "second (00..60)"
printf "%-10s %-25s %s\n"      "%t"            "`date +"%t"`"       "a tab"
printf "%-10s %-25s %s\n"      "%T"            "`date +"%T"`"       "time; same as %H:%M:%S"
printf "%-10s %-25s %s\n"      "%u"            "`date +"%u"`"       "day of week (1..7); 1 is Monday"
printf "%-10s %-25s %s\n"      "%U"            "`date +"%U"`"       "week number of year, with Sunday as first day of week (00..53)"
printf "%-10s %-25s %s\n"      "%V"            "`date +"%V"`"       "ISO week number, with Monday as first day of week (01..53)"
printf "%-10s %-25s %s\n"      "%w"            "`date +"%w"`"       "day of week (0..6); 0 is Sunday"
printf "%-10s %-25s %s\n"      "%W"            "`date +"%W"`"       "week number of year, with Monday as first day of week (00..53)"
printf "%-10s %-25s %s\n"      "%x"            "`date +"%x"`"       "locale's date representation (e.g., 12/31/99)"
printf "%-10s %-25s %s\n"      "%X"            "`date +"%X"`"       "locale's time representation (e.g., 23:13:48)"
printf "%-10s %-25s %s\n"      "%y"            "`date +"%y"`"       "last two digits of year (00..99)"
printf "%-10s %-25s %s\n"      "%Y"            "`date +"%Y"`"       "year"
printf "%-10s %-25s %s\n"      "%z"            "`date +"%z"`"       "+hhmm numeric timezone (e.g., -0400)"
printf "%-10s %-25s %s\n"      "%:z"           "`date +"%:z"`"      "+hh:mm numeric timezone (e.g., -04:00)"
printf "%-10s %-25s %s\n"      "%::z"          "`date +"%::z"`"     "+hh:mm:ss numeric time zone (e.g., -04:00:00)"
printf "%-10s %-25s %s\n"      "%:::z"         "`date +"%:::z"`"    "numeric  time  zone  with:  to necessary precision (e.g., -04, +05:30)"
printf "%-10s %-25s %s\n"      "%Z"            "`date +"%Z"`"       "alphabetic time zone abbreviation (e.g., EDT)"

